# Generated by Django 2.2.2 on 2019-07-15 02:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190704_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='event_num_ques',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
    ]
