# Generated by Django 2.2.2 on 2019-07-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
