# Generated by Django 2.2.2 on 2019-07-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190715_0759'),
        ('user_detail', '0002_auto_20190703_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganiserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organiser', models.BooleanField(default=False)),
                ('organiser_name', models.CharField(max_length=100)),
                ('organiser_email', models.EmailField(max_length=254)),
                ('organiser_contact', models.IntegerField()),
                ('organiser_password', models.CharField(max_length=100)),
                ('organiser_events', models.ManyToManyField(blank=True, to='events.Event')),
            ],
        ),
    ]
