# Generated by Django 2.2.2 on 2019-07-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantlevel',
            name='lastsub',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
