# Generated by Django 2.2.2 on 2019-07-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190704_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_model',
            name='question_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question_model',
            name='top_level',
            field=models.IntegerField(default=0),
        ),
    ]
